export declare const themes: {
    readonly light: {
        readonly background: "#ffffff";
        readonly surface: "#f8fafc";
        readonly elevated: "#ffffff";
        readonly text: "#0f172a";
        readonly mutedText: "#475569";
        readonly border: "#e2e8f0";
        readonly primary: "#126b4f";
        readonly primaryForeground: "#ffffff";
        readonly secondary: "#e2efe9";
        readonly secondaryForeground: "#0f172a";
        readonly success: "#0f8a5f";
        readonly warning: "#b7791f";
        readonly danger: "#dc2626";
        readonly info: "#2563eb";
    };
    readonly dark: {
        readonly background: "#020617";
        readonly surface: "#0f172a";
        readonly elevated: "#111827";
        readonly text: "#f8fafc";
        readonly mutedText: "#cbd5e1";
        readonly border: "#334155";
        readonly primary: "#34d399";
        readonly primaryForeground: "#020617";
        readonly secondary: "#1e293b";
        readonly secondaryForeground: "#f8fafc";
        readonly success: "#4ade80";
        readonly warning: "#fbbf24";
        readonly danger: "#f87171";
        readonly info: "#60a5fa";
    };
    readonly highContrast: {
        readonly background: "#000000";
        readonly surface: "#000000";
        readonly elevated: "#000000";
        readonly text: "#ffffff";
        readonly mutedText: "#ffffff";
        readonly border: "#ffffff";
        readonly primary: "#ffffff";
        readonly primaryForeground: "#000000";
        readonly secondary: "#ffffff";
        readonly secondaryForeground: "#000000";
        readonly success: "#ffffff";
        readonly warning: "#ffffff";
        readonly danger: "#ffffff";
        readonly info: "#ffffff";
    };
};
