export {
  Navbar,
  NavbarItem,
  type NavbarProps,
  type NavbarItemProps,
  BottomNav,
  BottomNavItem,
  type BottomNavProps,
  type BottomNavItemProps,
  Sidebar,
  SidebarHeader,
  SidebarBody,
  SidebarFooter,
  SidebarSection,
  SidebarItem,
  type SidebarProps,
  type SidebarItemProps,
  Breadcrumb,
  type BreadcrumbProps,
  type BreadcrumbItem,
  Pagination,
  type PaginationProps,
  Tabs,
  TabsList,
  TabsTrigger,
  TabsContent,
  type TabsProps,
  type TabsTriggerProps,
  type TabsContentProps,
} from "@nova/design-system";
