import type { Product, Category, Seller } from "@/types/domain";

export const SEED_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Fashion", slug: "fashion", productCount: 142 },
  { id: "cat-2", name: "Home & Living", slug: "home-living", productCount: 98 },
  { id: "cat-3", name: "Electronics", slug: "electronics", productCount: 67 },
  { id: "cat-4", name: "Organic Food", slug: "organic-food", productCount: 211 },
  { id: "cat-5", name: "Beauty & Care", slug: "beauty-care", productCount: 89 },
  { id: "cat-6", name: "Health & Wellness", slug: "health-wellness", productCount: 54 },
];

export const SEED_SELLERS: Seller[] = [
  {
    id: "sel-1",
    shopName: "EcoLight SL",
    slug: "ecolight-sl",
    description: "Renewable energy products crafted for West Africa.",
    rating: 4.8,
    totalSales: 1240,
    isVerified: true,
    isEcoCertified: true,
  },
  {
    id: "sel-2",
    shopName: "BoFarm Organics",
    slug: "bofarm-organics",
    description: "Certified organic produce from Bo District.",
    rating: 4.7,
    totalSales: 890,
    isVerified: true,
    isEcoCertified: true,
  },
  {
    id: "sel-3",
    shopName: "Freetown Threads",
    slug: "freetown-threads",
    description: "Sustainable fashion celebrating Sierra Leonean culture.",
    rating: 4.6,
    totalSales: 640,
    isVerified: true,
    isEcoCertified: false,
  },
  {
    id: "sel-4",
    shopName: "GreenRoot Home",
    slug: "greenroot-home",
    description: "Bamboo and recycled-material home goods.",
    rating: 4.5,
    totalSales: 410,
    isVerified: true,
    isEcoCertified: true,
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: "p-1",
    name: "Solar Lantern Pro",
    slug: "solar-lantern-pro",
    description: "12-hour solar-powered LED lantern, USB charging port, weather-resistant casing. Ideal for rural and urban homes.",
    priceSll: 320_000,
    stock: 48,
    category: SEED_CATEGORIES[2]!,
    seller: SEED_SELLERS[0]!,
    images: [{ id: "i-1", url: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=800&q=80", alt: "Solar Lantern Pro" }],
    isEcoCertified: true,
    ecoScore: 94,
    carbonImpact: "LOW",
    tags: ["solar", "energy", "eco"],
    isActive: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    id: "p-2",
    name: "Organic Cocoa Butter",
    slug: "organic-cocoa-butter",
    description: "Raw, unrefined cocoa butter sourced from certified Bo District farms. 100% natural, no additives.",
    priceSll: 240_000,
    stock: 80,
    category: SEED_CATEGORIES[4]!,
    seller: SEED_SELLERS[1]!,
    images: [{ id: "i-2", url: "https://images.unsplash.com/photo-1615486363973-f79cccbf9f5f?auto=format&fit=crop&w=800&q=80", alt: "Cocoa Butter" }],
    isEcoCertified: true,
    ecoScore: 90,
    carbonImpact: "LOW",
    tags: ["organic", "beauty", "natural"],
    isActive: true,
    isFeatured: true,
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "p-3",
    name: "Recycled Tote Bag",
    slug: "recycled-tote-bag",
    description: "Handwoven tote made from 100% recycled plastic bottles. Durable, washable, available in 6 patterns.",
    priceSll: 150_000,
    stock: 200,
    category: SEED_CATEGORIES[0]!,
    seller: SEED_SELLERS[2]!,
    images: [{ id: "i-3", url: "https://images.unsplash.com/photo-1614531341773-3bff8b7cb3fc?auto=format&fit=crop&w=800&q=80", alt: "Recycled Tote" }],
    isEcoCertified: false,
    ecoScore: 86,
    carbonImpact: "LOW",
    tags: ["fashion", "recycled", "sustainable"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 67,
  },
  {
    id: "p-4",
    name: "Bamboo Cutlery Set",
    slug: "bamboo-cutlery-set",
    description: "5-piece reusable bamboo cutlery set with travel pouch. Zero plastic, FSC-certified bamboo.",
    priceSll: 170_000,
    stock: 150,
    category: SEED_CATEGORIES[1]!,
    seller: SEED_SELLERS[3]!,
    images: [{ id: "i-4", url: "https://images.unsplash.com/photo-1584346133934-a3afd9a96ecf?auto=format&fit=crop&w=800&q=80", alt: "Bamboo Cutlery" }],
    isEcoCertified: true,
    ecoScore: 91,
    carbonImpact: "LOW",
    tags: ["bamboo", "kitchen", "zero-waste"],
    isActive: true,
    isFeatured: true,
    rating: 4.5,
    reviewCount: 43,
  },
  {
    id: "p-5",
    name: "Shea Butter Moisturiser",
    slug: "shea-butter-moisturiser",
    description: "Whipped shea butter enriched with vitamin E. Deep hydration for all skin types.",
    priceSll: 195_000,
    stock: 60,
    category: SEED_CATEGORIES[4]!,
    seller: SEED_SELLERS[1]!,
    images: [{ id: "i-5", url: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=800&q=80", alt: "Shea Butter" }],
    isEcoCertified: true,
    ecoScore: 88,
    carbonImpact: "LOW",
    tags: ["skincare", "organic", "shea"],
    isActive: true,
    isFeatured: false,
    rating: 4.9,
    reviewCount: 201,
  },
  {
    id: "p-6",
    name: "Wax Print Fabric Tee",
    slug: "wax-print-fabric-tee",
    description: "Classic Sierra Leonean kente-inspired wax print t-shirt, GOTS-certified cotton.",
    priceSll: 210_000,
    stock: 90,
    category: SEED_CATEGORIES[0]!,
    seller: SEED_SELLERS[2]!,
    images: [{ id: "i-6", url: "https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=800&q=80", alt: "Wax Print Tee" }],
    isEcoCertified: false,
    ecoScore: 78,
    carbonImpact: "MEDIUM",
    tags: ["fashion", "africa", "cotton"],
    isActive: true,
    isFeatured: true,
    rating: 4.4,
    reviewCount: 58,
  },
  {
    id: "p-7",
    name: "Moringa Superfood Powder",
    slug: "moringa-superfood-powder",
    description: "Organic moringa leaf powder, sun-dried and stone-ground. 250g resealable pouch.",
    priceSll: 180_000,
    stock: 110,
    category: SEED_CATEGORIES[3]!,
    seller: SEED_SELLERS[1]!,
    images: [{ id: "i-7", url: "https://images.unsplash.com/photo-1498557850523-fd3d118b962e?auto=format&fit=crop&w=800&q=80", alt: "Moringa Powder" }],
    isEcoCertified: true,
    ecoScore: 95,
    carbonImpact: "LOW",
    tags: ["superfood", "organic", "health"],
    isActive: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 136,
  },
  {
    id: "p-8",
    name: "Recycled Glass Vase",
    slug: "recycled-glass-vase",
    description: "Artisan vase hand-blown from 100% recycled glass by local Freetown artisans.",
    priceSll: 285_000,
    stock: 30,
    category: SEED_CATEGORIES[1]!,
    seller: SEED_SELLERS[3]!,
    images: [{ id: "i-8", url: "https://images.unsplash.com/photo-1612196808214-b7e239e5f6b7?auto=format&fit=crop&w=800&q=80", alt: "Glass Vase" }],
    isEcoCertified: true,
    ecoScore: 89,
    carbonImpact: "LOW",
    tags: ["home", "artisan", "recycled"],
    isActive: true,
    isFeatured: false,
    rating: 4.6,
    reviewCount: 22,
  },
];
